## InterConnect Meat Project
## ALSWH Study: Mid-age and Young cohorts 
## Aim: DATA process - derive variables for InterConnect Meat Project and Combine to one single file in .dta
## Exposures: involved multiple surveys
## by Chunxiao Li
## March 2021

# load R packages ---------------------------------------------------------

library(xlsx)
library(tidyverse)
library(readstata13)              #read stata13.stata14
library(haven)                    #read stata13.stata14
library(plyr)

# options(stringsAsFactors = F)

# load all files to combine -Young Cohort ----------------------------------------------------------

# list names of all files in a folder
in_files <- list.files( path = "V:/Studies/InterConnect/Internal/Meat exemplar/Data/ALSWH/A856stata/A856stata/Young Cohort", full.names = TRUE)
# load all files
df_alswh_y <- map( in_files, read_dta)
# check the files
df_alswh_y[[1]][1:3, 1:3]



# load all files to combine -Midage Cohort ----------------------------------------------------------

# list names of all files in a folder
in_files <- list.files( path = "V:/Studies/InterConnect/Internal/Meat exemplar/Data/ALSWH/A856stata/A856stata/Midage Cohort", full.names = TRUE)
# load all files
df_alswh_m <- map( in_files, read_dta)
# check the files
df_alswh_m[[1]][1:3, 1:3]




# derive variable list - young cohort ----------------------------------


# read in the file contains list of variables - derived from the documents generated by Hsinfang
setwd("V:/Studies/InterConnect/Internal/Meat exemplar/Data/ALSWH")
var_list <- read.xlsx ("Meta-data request meat and T2D_XX Study.xlsx",1, header = TRUE, stringsAsFactors = FALSE)

names(var_list) <- c("name")
var_list[1,1]

# split the variable names to single cells
var_ls <- 
        var_list %>% 
        select(name) %>% 
        separate( name, c("A", "B"), ":", extra = "merge")

var_ls_young <- 
        var_ls %>% 
        select( B) %>% 
        separate_rows( B, sep = ",") %>%  # split into single cells
        mutate( B = str_trim( B, side = "both")) # delete whitespace before/after strings


# derive variable list - Mid-age cohort ----------------------------------


setwd("V:/Studies/InterConnect/Internal/Meat exemplar/Data/ALSWH")
var_list <- read.xlsx ("Meta-data request meat and T2D_XX Study.xlsx", 2, header = TRUE, stringsAsFactors = FALSE)

names(var_list) <- c("name")
var_list[1,1]

# split the variable names to single cells
var_ls <- 
        var_list %>% 
        select(name) %>% 
        separate( name, c("A", "B"), ":", extra = "merge")

var_ls_midage <- 
        var_ls %>% 
        select( B) %>% 
        separate_rows( B, sep = ",") %>% 
        mutate( B = str_trim( B, side = "both")) 

# combine the variables needed - Young cohort -----------------------------


#  select variables in each dataframe of the list, loop through the list 
func_to_select_vars <- function(df){
         df <-   
         df %>% 
         rename_all( tolower) %>%
         select( colnames(.)[colnames(.) %in% varList]) 
}

id <- "idalias" 
varList <- c( id, tolower(var_ls_young$B)) 
df_alswh_deriv <- lapply(df_alswh_y, func_to_select_vars)

# combine each dataframe through the list -> a combined dataset 
dfs_alsw_young <- join_all(df_alswh_deriv, by = id, type = "full", match = "all" )
setdiff( varList, names(dfs_alsw_young)) 

        # explore why couldn`t find variable-y3exgrp ? - retired
        
        # dat <- df_alswh[[8]]
        # names(dat)
        # y3exgrp_ <- 
        #         dat %>% 
        #         select( contains("ex"))
        # names( y3exgrp_)

# combine the variables needed - Midage cohort ----------------------------------------------------------

#  select variables in each dataframe of the list, loop through the list 
func_to_select_vars <- function(df){
        df <- 
                df %>% 
                rename_all( tolower) %>%
                select( colnames(.)[colnames(.) %in% varList]) 
}

id <- "idalias" 
varList <- c( id, tolower(var_ls_midage$B))
df_alswh_deriv <- lapply(df_alswh_m, func_to_select_vars)


# combine each dataframe through the list -> a combined dataset 
dfs_alsw_midage <- join_all(df_alswh_deriv, by = id, type = "full", match = "all" )
setdiff( varList, names(dfs_alsw_midage)) 


# check overlap between young and old -------------------------------------

intersect( dfs_alsw_midage$idalias, dfs_alsw_young$idalias)
dim(dfs_alsw_midage)
dim(dfs_alsw_young)

# save dta files ----------------------------------------------------------
setwd("V:/Studies/InterConnect/Internal/Meat exemplar/Data/ALSWH/A856stata/A856stata_combine")

# write_dta( dfs_alsw_midage, "ALSWH_combined_MidAgeCohort.dta", label = attr( dfs_alsw_midage, "label"))
# write_dta( dfs_alsw_young, "ALSWH_combined_YoungCohort.dta", label = attr( dfs_alsw_young, "label"))

# write_dta( dfs_alsw_midage, "ALSWH_combined_MidAgeCohort_31032021.dta", label = attr( dfs_alsw_midage, "label"))
# write_dta( dfs_alsw_young, "ALSWH_combined_YoungCohort_31032021.dta", label = attr( dfs_alsw_young, "label"))

write_dta( dfs_alsw_midage, "ALSWH_combined_MidAgeCohort_04052021.dta", label = attr( dfs_alsw_midage, "label"))
write_dta( dfs_alsw_young, "ALSWH_combined_YoungCohort_04052021.dta", label = attr( dfs_alsw_young, "label"))

# check old and new dataset -----------------------------------------------
m_old <- read_dta("V:/Studies/InterConnect/Internal/Meat exemplar/Data/ALSWH/A856stata/A856stata_combine/ALSWH_combined_MidAgeCohort_04052021.dta", encoding = NULL)
y_old <- read_dta("V:/Studies/InterConnect/Internal/Meat exemplar/Data/ALSWH/A856stata/A856stata_combine/ALSWH_combined_YoungCohort_04052021.dta", encoding = NULL)

# m_old <- read_dta("V:/Studies/InterConnect/Internal/Meat exemplar/Data/ALSWH/A856stata/A856stata_combine/retired/ALSWH_combined_MidAgeCohort_31032021.dta", encoding = NULL)
# y_old <- read_dta("V:/Studies/InterConnect/Internal/Meat exemplar/Data/ALSWH/A856stata/A856stata_combine/retired/ALSWH_combined_YoungCohort_31032021.dta", encoding = NULL)

setdiff(names(dfs_alsw_midage), names(m_old))
setdiff(names(dfs_alsw_young), names(y_old))

table(y_old$y4q12c)

dim(y_old)
sum(is.na(y_old$y3age))
summary(y_old$y3age)
summary(y_old$y4age)

check <- 
  y_old %>% 
  mutate( age_na = case_when( is.na(y3age) ==TRUE & is.na(y4age)  ==TRUE & is.na(y5age)  ==TRUE &is.na( y6age)  ==TRUE & is.na(y7age)  ==TRUE & is.na(y8age)  ==TRUE ~ 1, 
                                              TRUE ~  0)) %>% 
  mutate( d_na = case_when ( is.na(y4q12c) == TRUE &  is.na(y5q12b) == TRUE  & is.na(y6q12b) == TRUE & is.na(y7q24b) == TRUE & is.na(y8q24b) == TRUE  ~ 1,
                             TRUE ~  0)) %>% 
  mutate( age_na_3 = case_when(  is.na(y4age)  ==TRUE & is.na(y5age)  ==TRUE &is.na( y6age)  ==TRUE & is.na(y7age)  ==TRUE & is.na(y8age)  ==TRUE ~ 1, 
                              TRUE ~  0)) %>% 
  
  select( age_na, d_na, y1age, y2age, y3age, y4age, y5age, y5age, y7age, y8age, y8q24b_age, age_na_3) %>% 
  filter(d_na ==0)

table( check$age_na_3)
table( check$d_na)          





# baseline desc -----------------------------------------------------------

y_old <- read_dta("V:/Studies/InterConnect/Internal/Meat exemplar/Data/ALSWH/A856stata/A856stata_combine/ALSWH_combined_YoungCohort_04052021.dta", encoding = NULL)

library(table1)

# Outcome variables (self-reported): 
# -	Diabetes (unspecified): y1q15a
# -	Type 2 diabetes: y2q12Ac, y2q12Bc, y3q12c, y4q12c, y5q12b, y6q12b, y7q24b, y8Q24b
# -	Type 1 diabetes: y2q12Ab, y2q12Bb, y3q12b, y4q12b, y5q12a, y6q12a, y7q24a, y8Q24a
# -	Age of first diagnosis of type 2 diabetes: y8q24b_age
# -	Age at baseline/last follow-up: y1age, y2age, y3age, y4age, y5age, y6age, y7age, y8age

out_var <- c("y1q15a", 
             "y2q12Ac", "y2q12Bc", "y3q12c", "y4q12c", "y5q12b", "y6q12b", "y7q24b", "y8Q24b",
             "y2q12Ab", "y2q12Bb", "y3q12b", "y4q12b", "y5q12a", "y6q12a", "y7q24a", "y8Q24a",
             "y8q24b_age",
             "y1age", "y2age", "y3age", "y4age", "y5age", "y6age", "y7age", "y8age")

out_var <- tolower(out_var)

df_y <- 
  y_old %>% 
  select(out_var, idalias) %>% 
  mutate( prev = case_when( (y1q15a ==1 |  y2q12ac ==1 | y2q12bc==1 | 
                             y3q12c==1 |  y2q12ab==1 |  y2q12bb==1 | 
                             y3q12b ==1 | y4q12b==1 | y5q12a ==1 |  y6q12a ==1 | y7q24a ==1 | y8q24a==1) ~ 1, 
                           TRUE ~ 0)
          ) %>% 
  
  mutate( miss = case_when ( (is.na(y4q12c) == TRUE & is.na(y5q12b) == TRUE & is.na(y6q12b) == TRUE & is.na(y7q24b) == TRUE & is.na(y8q24b) == TRUE) ~ 1, 
                             TRUE ~ 0))
          
          
  # select(prev, y1q15a, y2q12ac, y2q12bc, y3q12c, y2q12ab, y2q12bb, y3q12b, y4q12b, y5q12a, y6q12a, y7q24a, y8q24a)


table(df_y$prev) # 341 prev cases to exclude
table(df_y$miss)

df_base <-
  df_y %>% 
  filter( ! is.na(y3age)) %>% 
  filter( prev!= 1) %>% 


  mutate( y1q15a = structure( as_factor(y1q15a), units = "Ever told you have diabetes in survey 1"),
          y8q24b_age = structure( y8q24b_age, label = "age first dignosed as T2D"),
          y2q12ac = structure(as_factor(y2q12ac), units = "survey2"),
          y2q12bc = structure(as_factor(y2q12bc), units = "survey2"),
          y3q12c = structure(as_factor(y3q12c), units = "survey3"),
          y4q12c = structure(as_factor(y4q12c), units = "survey4"),
          y5q12b = structure(as_factor(y5q12b), units = "survey5"),
          y6q12b = structure(as_factor(y6q12b), units = "survey6"),
          y7q24b = structure(as_factor(y7q24b), units = "survey7"),
          y8q24b = structure(as_factor(y8q24b), units = "survey8"),
          
          y2q12ab = structure(as_factor(y2q12ab), units = "survey2"),
          y2q12bb = structure(as_factor(y2q12bb), units = "survey2"),
          y3q12b = structure(as_factor(y3q12b), units = "survey3"),
          y4q12b = structure(as_factor(y4q12b), units = "survey4"),
          y5q12a = structure(as_factor(y5q12a), units = "survey5"),
          y6q12a = structure(as_factor(y6q12a), units = "survey6"),
          y7q24a = structure(as_factor(y7q24a), units = "survey7"),
          y8q24a = structure(as_factor(y8q24a), units = "survey8")
          )
# label(df_base$y8q24b)
check <- 
  df_base %>% 
  # select(y4q12c, y4age, y5q12b, y5age,  y6q12b, y6age, y7q24b, y7age, y8q24b, y8age, miss) %>% 
  filter(miss ==1)

table(df_base$miss)
table1(~ y3age + y4age + y5age + y6age + y7age + y8age + 
         y1q15a + 
         y8q24b_age + 
         y2q12ac  + y2q12bc + y3q12c + y4q12c + y5q12b  + y6q12b + y7q24b +y8q24b + #type2
         y2q12ab  + y2q12bb  + y3q12b  + y4q12b  + y5q12a  + y6q12a  + y7q24a  + y8q24a,  #type1
         
       data=df_base)

str(df_base)
  
names(y_old)
